### PR TITLE
python 3 support :bangbang:

### PR DESCRIPTION
**Pull request by krockode**
:zap: Add python 3 support :zap:

tested on python 2 and 3.

Thanks for the library.

### CODE REVIEW

**Comment by glasnt** [comment]
Thank you for this! 

I need to work out how to independently test this PR before I merge it, which requires learning virtual env. Any hints/links?

**Comment by krockode** [comment]
No worries, I use [virtualenvwrapper](https://virtualenvwrapper.readthedocs.org/en/latest/) which is a wrapper around virtualenv that makes using it simpler.  Install it like this:

    $ pip install virtualenvwrapper
    $ source virtualenvwrapper.sh # put this in bashrc / zshrc

then create the virtual envs for python 2 and 3:

    cd ~/src/octohat
    # make a virtual env with a project path set to the git checkout
    mkvirtualenv -a `pwd` -p /usr/local/bin/python2 octohat2
    mkvirtualenv -a `pwd` -p /usr/local/bin/python3 octohat3

Then work on one of them (which includes cd-ing to the project dir)

    $ workon octohat2
    $ pip install --editable .

**Comment by glasnt** [comment]
I think I got this working locally, and I think it's working with python3. 

Thank you :D

**Comment by glasnt** [comment]
And by 'think', I mean it actually does. Because this works in Travis CI now. :smiley:

**Pull request merged**
